name = "echoes-social"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "echoes-db"
database_id = "90553ad1-8008-4c61-9210-7314b0a6730f"

[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "echoes-audio"

[vars]
ENVIRONMENT = "production"
CLERK_JWKS_URL = "https://regular-feline-15.clerk.accounts.dev/.well-known/jwks.json"
R2_PUBLIC_BASE_URL = "https://media.echoeslife.com"
